[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd services/metrics-updater-worker && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "5004"
WORKER_INTERVAL = "3600000"
NODE_ENV = "production"

